_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 23
INPUT:
  MIN_SIZE_TRAIN: (1080, )
  MIN_SIZE_TEST: 1080
  MAX_SIZE_TRAIN: 1920
  MAX_SIZE_TEST: 1920
SOLVER:
  BASE_LR: 0.0005
  IMS_PER_BATCH: 4
  STEPS: (210000, 250000)
  MAX_ITER: 270000
DATALOADER:
  NUM_WORKERS: 4